// @flow
export const APPEND_POINT: 'APPEND_POINT' = 'APPEND_POINT';

export const APPEND_STROKE: 'APPEND_STROKE' = 'APPEND_STROKE';

export const FINISH_STROKE: 'FINISH_STROKE' = 'FINISH_STROKE';

export const TOGGLE_PLOMA: 'TOGGLE_PLOMA' = 'TOGGLE_PLOMA';

export const JUMP_TO: 'JUMP_TO' = 'JUMP_TO';

export const UPDATE_THRESHOLD: 'UPDATE_THRESHOLD' = 'UPDATE_THRESHOLD';

export const UPDATE_POSITION: 'UPDATE_POSITION' = 'UPDATE_POSITION';

export const ROTATE_BY: 'ROTATE_BY' = 'ROTATE_BY';

export const HIDE: 'HIDE' = 'HIDE';

export const SELECT: 'SELECT' = 'SELECT';

export const TOGGLE_HANDWRITING_RECOGNITION: 'TOGGLE_HANDWRITING_RECOGNITION' = 'TOGGLE_HANDWRITING_RECOGNITION';

export const TOGGLE_DRAWING: 'TOGGLE_DRAWING' = 'TOGGLE_DRAWING';

export const OBSERVE_MUTATIONS: 'OBSERVE_MUTATIONS' = 'OBSERVE_MUTATIONS';

export const SET_SCENE_INDEX: 'SET_SCENE_INDEX' = 'SET_SCENE_INDEX';

export const ADD_SCENE: 'ADD_SCENE' = 'ADD_SCENE';

export const ADD_SCENE_AT: 'ADD_SCENE_AT' = 'ADD_SCENE_AT';

export const NEXT_SCENE: 'NEXT_SCENE' = 'NEXT_SCENE';

export const PREVIOUS_SCENE: 'PREVIOUS_SCENE' = 'PREVIOUS_SCENE';

export const SELECT_INSIDE: 'SELECT_INSIDE' = 'SELECT_INSIDE';

export const TOGGLE_INTERPRETER: 'TOGGLE_INTERPRETER' = 'TOGGLE_INTERPRETER';

export const RECOGNIZE_HANDWRITING: 'RECOGNIZE_HANDWRITING' = 'RECOGNIZE_HANDWRITING';

export const REQUEST_TEXT_CANDIDATES: 'REQUEST_TEXT_CANDIDATES' = 'REQUEST_TEXT_CANDIDATES';

export const REQUEST_SHAPE_CANDIDATES: 'REQUEST_SHAPE_CANDIDATES' = 'REQUEST_SHAPE_CANDIDATES';

export const RECEIVE_SHAPE_CANDIDATES: 'RECEIVE_SHAPE_CANDIDATES' = 'RECEIVE_SHAPE_CANDIDATES';

export const RECEIVE_TEXT_CANDIDATES: 'RECEIVE_TEXT_CANDIDATES' = 'RECEIVE_TEXT_CANDIDATES';

export const TEXT_CANDIDATES_FETCH_REQUESTED: 'TEXT_CANDIDATES_FETCH_REQUESTED' = 'TEXT_CANDIDATES_FETCH_REQUESTED';

export const SHAPE_CANDIDATES_FETCH_REQUESTED: 'SHAPE_CANDIDATES_FETCH_REQUESTED' = 'SHAPE_CANDIDATES_FETCH_REQUESTED';

export const APPEND_SPECIFC_ACTION: 'APPEND_SPECIFC_ACTION' = 'APPEND_SPECIFC_ACTION';
