export const APPEND_POINT = 'APPEND_POINT';

export const CREATE_STROKE = 'CREATE_STROKE';

export const FINISH_STROKE = 'FINISH_STROKE';

export const TOGGLE_PLOMA = 'TOGGLE_PLOMA';

export const JUMP_TO = 'JUMP_TO';

export const UPDATE_THRESHOLD = 'UPDATE_THRESHOLD';

export const UPDATE_POSITION = 'UPDATE_POSITION';

export const HIDE = 'HIDE';

export const SELECT = 'SELECT';

export const TOGGLE_HANDWRITING_RECOGNITION = 'TOGGLE_HANDWRITING_RECOGNITION';

export const TOGGLE_DRAWING = 'TOGGLE_DRAWING';

export const OBSERVE_MUTATIONS = 'OBSERVE_MUTATIONS';

export const SET_SCENE_INDEX = 'SET_SCENE_INDEX';

export const ADD_SCENE = 'ADD_SCENE';

export const ADD_SCENE_AT = 'ADD_SCENE_AT';

export const NEXT_SCENE = 'NEXT_SCENE';

export const PREVIOUS_SCENE = 'PREVIOUS_SCENE';

export const SELECT_INSIDE = 'SELECT_INSIDE';